### ISSUE TITLE
Messages being joined

### ISSUE THREAD

**Issue by fullheartgames** [CodeSpartan/UE4TcpSocketPlugin#10]
Our team have noticed messages received in quick succession are being joined together. We thought maybe it was being caused by the Nagle algorithm but disabling this did not help.  Any ideas would be greatly appreciated, thanks!

**Comment by CodeSpartan** [comment]
The TCP protocol has no notion of message boundaries, so that's expected and normal. Prepend the message length to each message. 
Read it so that you're always attempting to read the message's length first, then N bytes that you know are the actual message, and then do the same thing again as many times as necessary, because there may be multiple messages packed into one.

Same question as yours: https://serverfault.com/questions/745321/tcp-messages-merged

**Comment by fullheartgames** [comment]
Sorry that's our bad, we realized this after a little more research. Thank you so much for the speedy response!
