### ISSUE TITLE
Binaries folder consume lots of memory

### ISSUE THREAD

**Issue by zhongquanchen** [CodeSpartan/UE4TcpSocketPlugin#14]
![image](https://user-images.githubusercontent.com/27601467/147802091-845aa7d7-38c1-4ae8-aef6-d5a71c70e914.png)
Hi, I have a question regarding the plugin. When I use it, it will generate lots of .pdb files and it consume lots of memory in my disk. 
![image](https://user-images.githubusercontent.com/27601467/147802143-df647ff7-68e6-465f-8e8a-16c168b1cc2c.png)
I don't know if the pdb files was necessary for the plugin.

**Comment by CodeSpartan** [comment]
It's a symptom of something being wrong with your version of ue4/visual studio, not the plugin.
The pdb files are needed for debugging. Every time you rebuild, the old one gets deleted, the new one gets created. In your case, the old one gets renamed instead and they keep piling up. 
In a debug build, you should only have one such file out of all of these. In a shipping build, probably zero.
Ask the question on the forums or answerhub. It's not caused by the plugin.
